name: bench-ckb-bench-server

on:
  workflow_dispatch:

jobs:

  benchmark:
    name: Benchmark
    runs-on: ubuntu-20.04
    env:
      SSH_ID: ${{ secrets.SSH_ID }}
      SSH_ID_PUB: ${{ secrets.SSH_ID_PUB }}
      GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
      ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Start
        run: |
          cd ckb-bench-server
          bash run.sh

      - name: Set test state when benchmark failed.
        id: state
        if: ${{ failure() }}
        run: echo "GITHUB_RUN_STATE=1" >> $GITHUB_OUTPUT

      - name: Publish reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: jfoa-build-reports-${{ runner.os }}
          path: ckb-bench-server/job/benchmark-in-10h/ansible/logs
      - name: Clean Up
        if: ${{ steps.UpdateCkb.outputs.GITHUB_RUN_STATE == '1' }}
        run: |
          bash /home/runner/work/ckb-integration-test/ckb-integration-test/ckb-bench-server/script/benchmark.sh clean
